#############################################################################################################
STALKER ERROR LOG ###########################################################################################
#############################################################################################################

#############################################################################################################
05/08/2017 | 21:01:44

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/root/testing/stalker/profiles/"+vars.first_name+"_"+vars.last_name+".txt",'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Trey+Austin+Waldrop&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f607524de50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:44

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Trey+Austin+Waldrop&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:46

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/root/testing/stalker/profiles/"+vars.first_name+"_"+vars.last_name+".txt",'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.findmugshots.com', port=443): Max retries exceeded with url: /arrests/Trey_Waldrop_KY (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f607524db90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:46

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://www.findmugshots.com/arrests/Trey_Waldrop_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:48

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/root/testing/stalker/profiles/"+vars.first_name+"_"+vars.last_name+".txt",'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='mugshots.com', port=80): Max retries exceeded with url: /search.html?q=Trey+Waldrop (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f607524d810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:48

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://mugshots.com/search.html?q=Trey+Waldrop', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:50

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/root/testing/stalker/profiles/"+vars.first_name+"_"+vars.last_name+".txt",'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='whitepages.plus', port=443): Max retries exceeded with url: /n/Trey_Waldrop/location/Elkton%252C_KY (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f607524ded0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:50

                out = subprocess.check_output(["wget","-qO-",url, "|", "html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://whitepages.plus/n/Trey_Waldrop/location/Elkton%252C_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:52

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/root/testing/stalker/profiles/"+vars.first_name+"_"+vars.last_name+".txt",'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.zabasearch.com', port=80): Max retries exceeded with url: /people/Trey+Waldrop/KY/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f607524de10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:52

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://www.zabasearch.com/people/Trey+Waldrop/KY/', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:54

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/root/testing/stalker/profiles/"+vars.first_name+"_"+vars.last_name+".txt",'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.peekyou.com', port=80): Max retries exceeded with url: /usa/Kentucky/Trey_Waldrop (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f607524d110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:54

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'http://www.peekyou.com/usa/Kentucky/Trey_Waldrop', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:56

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/root/testing/stalker/profiles/"+vars.first_name+"_"+vars.last_name+".txt",'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.spokeo.com', port=443): Max retries exceeded with url: /Trey-Waldrop (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f607524db90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:57

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.spokeo.com/Trey-Waldrop', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:59

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/root/testing/stalker/profiles/"+vars.first_name+"_"+vars.last_name+".txt",'a') as profile:
                profile.write("\
##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.linkedin.com', port=443): Max retries exceeded with url: /pub/dir/Trey/Waldrop?trk=uno-reg-guest-home-name-search (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f607524de10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:01:59

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.linkedin.com/pub/dir/Trey/Waldrop?trk=uno-reg-guest-home-name-search', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
05/08/2017 | 21:02:01

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/root/testing/stalker/profiles/"+vars.first_name+"_"+vars.last_name+".txt",'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f607524d4d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
06/08/2017 | 14:23:03
gears.read_profile()
[Errno 2] No such file or directory: '/usr/share/stalker/profiles/.Trey_Austin_Waldrop'
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:36
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:37
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:37
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:37
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:37
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:37
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:38
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:38
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:38
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:38
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:38
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:42
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:42
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:42
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:43
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:43
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:44
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:44
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:44
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:44
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:44
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:44
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:44
os.system(": > /usr/share/stalker/profiles/."+vars.name)
'module' object has no attribute 'name'
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:44
subprocess.call(["rm","/usr/share/stalker/profiles/.",vars.name])
'module' object has no attribute 'name'
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:18:44
os.system("rm /usr/share/stalker/profiles/."+vars.name)
'module' object has no attribute 'name'
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:22:57
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:22:57
os.system(": > /usr/share/stalker/profiles/."+vars.name)
'module' object has no attribute 'name'
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:22:57
subprocess.call(["rm","/usr/share/stalker/profiles/.",vars.name])
'module' object has no attribute 'name'
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:22:57
os.system("rm /usr/share/stalker/profiles/."+vars.name)
'module' object has no attribute 'name'
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:41:16
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:46:17
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:51:54
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:51:55
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:51:55
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:51:55
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:53:33
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:56:18
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:56:18
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:57:28
gears.read_profile()
[Errno 2] No such file or directory: '/usr/share/stalker/profiles/.Kimber_Leigh_Smith'
#############################################################################################################
#############################################################################################################
06/08/2017 | 21:58:43
gears.read_profile()
[Errno 2] No such file or directory: '/usr/share/stalker/profiles/.Kimber_Leigh_Smith'
#############################################################################################################
#############################################################################################################
07/08/2017 | 20:47:04
gears.profile_manager()
global name 'target' is not defined
#############################################################################################################
#############################################################################################################
07/08/2017 | 22:12:11
gears.profile_manager()
global name 'target' is not defined
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:16:04
stalker opt == add
[Errno 2] No such file or directory: '/usr/share/stalker/profiles/%s/%s.txt'
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:17:19
stalker opt == add
[Errno 2] No such file or directory: '/usr/share/stalker/profiles/%s/%s.txt'
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:18:29
stalker opt == add
[Errno 2] No such file or directory: '/usr/share/stalker/profiles/%s/%s.txt'
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:19:45
stalker opt == add
[Errno 2] No such file or directory: '/usr/share/stalker/profiles/%s/%s.txt'
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:23:07
stalker opt == add
[Errno 2] No such file or directory: '/usr/share/stalker/profiles/%s/%s.txt'
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:23:34
stalker opt == add
[Errno 2] No such file or directory: '/usr/share/stalker/profiles/%s/%s.txt'
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:27:26
gears.profile_manager()
full_info() takes exactly 17 arguments (9 given)
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:28:51
gears.profile_manager()
full_info() takes exactly 17 arguments (9 given)
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:33:07
gears.profile_manager()
full_info() takes exactly 17 arguments (9 given)
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:34:34
gears.profile_manager()
full_info() takes exactly 17 arguments (9 given)
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:43:00
gears.profile_manager()
full_info() takes exactly 17 arguments (9 given)
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:48:27
gears.profile_manager()
full_info() takes exactly 17 arguments (9 given)
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:49:46
gears.profile_manager()
full_info() takes exactly 17 arguments (9 given)
#############################################################################################################
#############################################################################################################
07/08/2017 | 23:55:06
gears.profile_manager()
full_info() takes exactly 17 arguments (9 given)
#############################################################################################################
#############################################################################################################
08/08/2017 | 00:10:27
gears.profile_manager()
Invalid URL 'Fakebook.com': No schema supplied. Perhaps you meant http://Fakebook.com?
#############################################################################################################
#############################################################################################################
08/08/2017 | 00:32:27
gears.profile_manager()
Invalid URL '': No schema supplied. Perhaps you meant http://?
#############################################################################################################
#############################################################################################################
08/08/2017 | 00:34:09

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Elizabeth+Dawn+Gant&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb254548ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
08/08/2017 | 00:34:09

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Elizabeth+Dawn+Gant&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
08/08/2017 | 00:34:11

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.findmugshots.com', port=443): Max retries exceeded with url: /arrests/Elizabeth_Gant_KY (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fb254548290>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
08/08/2017 | 00:34:11

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://www.findmugshots.com/arrests/Elizabeth_Gant_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
08/08/2017 | 00:51:50
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
08/08/2017 | 00:51:50
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
08/08/2017 | 20:26:46
gears.profile_manager()
full_info() takes exactly 17 arguments (9 given)
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:06:20
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:06:20
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:09:08
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:09:08
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:28

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Trey+Austin+Waldrop&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbdf770d510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:29

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Trey+Austin+Waldrop&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:31

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.findmugshots.com', port=443): Max retries exceeded with url: /arrests/Trey_Waldrop_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbdf770d6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:31

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://www.findmugshots.com/arrests/Trey_Waldrop_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:33

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='mugshots.com', port=80): Max retries exceeded with url: /search.html?q=Trey+Waldrop (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdf770d690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:33

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://mugshots.com/search.html?q=Trey+Waldrop', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:35

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='whitepages.plus', port=443): Max retries exceeded with url: /n/Trey_Waldrop/location/Elkton%252C_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbdf770d6d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:35

                out = subprocess.check_output(["wget","-qO-",url, "|", "html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://whitepages.plus/n/Trey_Waldrop/location/Elkton%252C_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:37

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.zabasearch.com', port=80): Max retries exceeded with url: /people/Trey+Waldrop/KY/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdf770d490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:37

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://www.zabasearch.com/people/Trey+Waldrop/KY/', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:39

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.peekyou.com', port=80): Max retries exceeded with url: /usa/Kentucky/Trey_Waldrop (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbdf770d810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:39

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'http://www.peekyou.com/usa/Kentucky/Trey_Waldrop', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:41

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.spokeo.com', port=443): Max retries exceeded with url: /Trey-Waldrop (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbdf770d510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:41

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.spokeo.com/Trey-Waldrop', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:43

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.linkedin.com', port=443): Max retries exceeded with url: /pub/dir/Trey/Waldrop?trk=uno-reg-guest-home-name-search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbdf770d3d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:43

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.linkedin.com/pub/dir/Trey/Waldrop?trk=uno-reg-guest-home-name-search', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:44:45

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fbdf770d850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:51:11
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
10/08/2017 | 20:51:11
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:10

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.stalked(data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Trey+Austin+Waldrop&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2bce4184d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:10

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Trey+Austin+Waldrop&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:12

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.findmugshots.com', port=443): Max retries exceeded with url: /arrests/Trey_Waldrop_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2bce418690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:13

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://www.findmugshots.com/arrests/Trey_Waldrop_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:15

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='mugshots.com', port=80): Max retries exceeded with url: /search.html?q=Trey+Waldrop (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bce418650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:15

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://mugshots.com/search.html?q=Trey+Waldrop', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:17

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='whitepages.plus', port=443): Max retries exceeded with url: /n/Trey_Waldrop/location/Elkton%252C_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2bce418690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:17

                out = subprocess.check_output(["wget","-qO-",url, "|", "html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://whitepages.plus/n/Trey_Waldrop/location/Elkton%252C_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:19

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.zabasearch.com', port=80): Max retries exceeded with url: /people/Trey+Waldrop/KY/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bce418450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:19

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://www.zabasearch.com/people/Trey+Waldrop/KY/', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:21

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.peekyou.com', port=80): Max retries exceeded with url: /usa/Kentucky/Trey_Waldrop (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2bce4187d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:27:21

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'http://www.peekyou.com/usa/Kentucky/Trey_Waldrop', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:55:25
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:55:25
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:58:52

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.stalked(data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Jessie+Dwayne+James&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcaa45eb750>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:58:52

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Jessie+Dwayne+James&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:58:54

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.findmugshots.com', port=443): Max retries exceeded with url: /arrests/Jessie_James_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcaa45eb910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:58:54

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://www.findmugshots.com/arrests/Jessie_James_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:58:56

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='mugshots.com', port=80): Max retries exceeded with url: /search.html?q=Jessie+James (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcaa45eb8d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:58:56

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://mugshots.com/search.html?q=Jessie+James', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:58:58

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='whitepages.plus', port=443): Max retries exceeded with url: /n/Jessie_James/location/Elkton%252C_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcaa45eb5d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:58:58

                out = subprocess.check_output(["wget","-qO-",url, "|", "html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://whitepages.plus/n/Jessie_James/location/Elkton%252C_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:59:00

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.zabasearch.com', port=80): Max retries exceeded with url: /people/Jessie+James/KY/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcaa45eb210>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:59:00

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://www.zabasearch.com/people/Jessie+James/KY/', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:59:02

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.peekyou.com', port=80): Max retries exceeded with url: /usa/Kentucky/Jessie_James (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcaa45eba50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:59:02

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'http://www.peekyou.com/usa/Kentucky/Jessie_James', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:59:04

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.spokeo.com', port=443): Max retries exceeded with url: /Jessie-James (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcaa45eb050>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:59:04

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.spokeo.com/Jessie-James', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:59:06

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.linkedin.com', port=443): Max retries exceeded with url: /pub/dir/Jessie/James?trk=uno-reg-guest-home-name-search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcaa45eb910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:59:07

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.linkedin.com/pub/dir/Jessie/James?trk=uno-reg-guest-home-name-search', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 22:59:09

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcaa45eba90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:41

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.stalked(data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Johnny+Jay+Walker&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2a4c194d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:41

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Johnny+Jay+Walker&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:43

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.findmugshots.com', port=443): Max retries exceeded with url: /arrests/Johnny_Walker_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2a4c19690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:43

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://www.findmugshots.com/arrests/Johnny_Walker_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:45

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='mugshots.com', port=80): Max retries exceeded with url: /search.html?q=Johnny+Walker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2a4c19610>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:45

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://mugshots.com/search.html?q=Johnny+Walker', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:47

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='whitepages.plus', port=443): Max retries exceeded with url: /n/Johnny_Walker/location/Elkton%252C_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2a4c19450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:48

                out = subprocess.check_output(["wget","-qO-",url, "|", "html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://whitepages.plus/n/Johnny_Walker/location/Elkton%252C_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:50

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.zabasearch.com', port=80): Max retries exceeded with url: /people/Johnny+Walker/KY/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2a4c192d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:50

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://www.zabasearch.com/people/Johnny+Walker/KY/', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:52

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.peekyou.com', port=80): Max retries exceeded with url: /usa/Kentucky/Johnny_Walker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa2a4c197d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:52

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'http://www.peekyou.com/usa/Kentucky/Johnny_Walker', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:54

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.spokeo.com', port=443): Max retries exceeded with url: /Johnny-Walker (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2a4c19490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:54

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.spokeo.com/Johnny-Walker', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:56

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.linkedin.com', port=443): Max retries exceeded with url: /pub/dir/Johnny/Walker?trk=uno-reg-guest-home-name-search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2a4c19510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:56

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.linkedin.com/pub/dir/Johnny/Walker?trk=uno-reg-guest-home-name-search', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:04:58

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa2a4c19810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:25

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.stalked(data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Jeremiah+Jay+Bullfrog&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e43287510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:25

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Jeremiah+Jay+Bullfrog&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:27

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.findmugshots.com', port=443): Max retries exceeded with url: /arrests/Jeremiah_Bullfrog_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e43287690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:27

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://www.findmugshots.com/arrests/Jeremiah_Bullfrog_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:29

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='mugshots.com', port=80): Max retries exceeded with url: /search.html?q=Jeremiah+Bullfrog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e43287550>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:29

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://mugshots.com/search.html?q=Jeremiah+Bullfrog', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:31

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='whitepages.plus', port=443): Max retries exceeded with url: /n/Jeremiah_Bullfrog/location/Elkton%252C_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e43287510>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:31

                out = subprocess.check_output(["wget","-qO-",url, "|", "html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://whitepages.plus/n/Jeremiah_Bullfrog/location/Elkton%252C_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:33

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.zabasearch.com', port=80): Max retries exceeded with url: /people/Jeremiah+Bullfrog/KY/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e432873d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:33

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://www.zabasearch.com/people/Jeremiah+Bullfrog/KY/', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:35

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.peekyou.com', port=80): Max retries exceeded with url: /usa/Kentucky/Jeremiah_Bullfrog (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3e43287590>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:36

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'http://www.peekyou.com/usa/Kentucky/Jeremiah_Bullfrog', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:38

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.spokeo.com', port=443): Max retries exceeded with url: /Jeremiah-Bullfrog (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e432876d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:38

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.spokeo.com/Jeremiah-Bullfrog', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:40

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.linkedin.com', port=443): Max retries exceeded with url: /pub/dir/Jeremiah/Bullfrog?trk=uno-reg-guest-home-name-search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e43287650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:40

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.linkedin.com/pub/dir/Jeremiah/Bullfrog?trk=uno-reg-guest-home-name-search', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:08:42

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.stalked(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e43287490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:11:06

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.stalked(data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Jeremiah+Jay+Bullfrog&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e43287390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:11:06

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Jeremiah+Jay+Bullfrog&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:11:15

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.stalked(data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Jeremiah+Jay+Bullfrog&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f3e432876d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
10/08/2017 | 23:11:16

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Jeremiah+Jay+Bullfrog&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:20

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.personal(data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Bruce+Willy+Wayne&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f85b0b604d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:20

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Bruce+Willy+Wayne&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:22

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.findmugshots.com', port=443): Max retries exceeded with url: /arrests/Bruce_Wayne_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f85b0b60690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:22

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://www.findmugshots.com/arrests/Bruce_Wayne_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:24

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='mugshots.com', port=80): Max retries exceeded with url: /search.html?q=Bruce+Wayne (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85b0b60650>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:24

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://mugshots.com/search.html?q=Bruce+Wayne', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:26

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='whitepages.plus', port=443): Max retries exceeded with url: /n/Bruce_Wayne/location/Elkton%252C_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f85b0b60690>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:26

                out = subprocess.check_output(["wget","-qO-",url, "|", "html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://whitepages.plus/n/Bruce_Wayne/location/Elkton%252C_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:28

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.zabasearch.com', port=80): Max retries exceeded with url: /people/Bruce+Wayne/KY/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85b0b60450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:28

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://www.zabasearch.com/people/Bruce+Wayne/KY/', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:30

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.peekyou.com', port=80): Max retries exceeded with url: /usa/Kentucky/Bruce_Wayne (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f85b0b607d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:30

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'http://www.peekyou.com/usa/Kentucky/Bruce_Wayne', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:32

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.spokeo.com', port=443): Max retries exceeded with url: /Bruce-Wayne (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f85b0b604d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:32

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.spokeo.com/Bruce-Wayne', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:34

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.linkedin.com', port=443): Max retries exceeded with url: /pub/dir/Bruce/Wayne?trk=uno-reg-guest-home-name-search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f85b0b60390>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:34

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.linkedin.com/pub/dir/Bruce/Wayne?trk=uno-reg-guest-home-name-search', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 13:02:37

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f85b0b60810>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:44

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            print (data)
            tpro.personal(data)

HTTPSConnectionPool(host='www.pipl.com', port=443): Max retries exceeded with url: /search/?q=Jimmy+Jim+Jimson&l=Elkton%2C+Kentucky&sloc=US%7CKY%7CElkton&in=5 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd9ff31fa10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:44

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(out)

Command '['wget', '-qO-', 'https://www.pipl.com/search/?q=Jimmy+Jim+Jimson&l=Elkton%2C+Kentucky&sloc=US|KY|Elkton&in=5', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:46

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.findmugshots.com', port=443): Max retries exceeded with url: /arrests/Jimmy_Jimson_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd9ff31fe10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:46

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://www.findmugshots.com/arrests/Jimmy_Jimson_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:48

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='mugshots.com', port=80): Max retries exceeded with url: /search.html?q=Jimmy+Jimson (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9ff31f7d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:48

            out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
            print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://mugshots.com/search.html?q=Jimmy+Jimson', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:50

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='whitepages.plus', port=443): Max retries exceeded with url: /n/Jimmy_Jimson/location/Elkton%252C_KY (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd9ff31fd10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:50

                out = subprocess.check_output(["wget","-qO-",url, "|", "html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'https://whitepages.plus/n/Jimmy_Jimson/location/Elkton%252C_KY', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:52

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.zabasearch.com', port=80): Max retries exceeded with url: /people/Jimmy+Jimson/KY/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9ff31f710>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:52

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(colored(out,'red',attrs=['bold']))

Command '['wget', '-qO-', 'http://www.zabasearch.com/people/Jimmy+Jimson/KY/', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:54

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPConnectionPool(host='www.peekyou.com', port=80): Max retries exceeded with url: /usa/Kentucky/Jimmy_Jimson (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fd9ff349110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:54

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'http://www.peekyou.com/usa/Kentucky/Jimmy_Jimson', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:56

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.spokeo.com', port=443): Max retries exceeded with url: /Jimmy-Jimson (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd9ff31fc90>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:56

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.spokeo.com/Jimmy-Jimson', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:58

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.linkedin.com', port=443): Max retries exceeded with url: /pub/dir/Jimmy/Jimson?trk=uno-reg-guest-home-name-search (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd9ff349150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:50:58

                out = subprocess.check_output(["wget","-qO-",url,"|","html2text"])
                print(out)

Command '['wget', '-qO-', 'https://www.linkedin.com/pub/dir/Jimmy/Jimson?trk=uno-reg-guest-home-name-search', '|', 'html2text']' returned non-zero exit status 4
#############################################################################################################
#############################################################################################################
11/08/2017 | 15:51:01

            page = requests.get(url)
            html = page.text
            text_only = bs(html, 'html.parser')
            text = text_only.get_text()
            data = text.encode('ascii', 'ignore').decode('ascii')
            tpro.personal(data)
            with open("/usr/share/stalker/profiles/%s/%s.txt"% (vars.full_name, vars.full_name),'a') as profile:
                profile.write("\n##################################################################################################")
                profile.write("\n"+data+"\n\n\n")
                profile.close()

HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fd9ff349150>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))
#############################################################################################################
#############################################################################################################
11/08/2017 | 16:01:35
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 9] Bad file descriptor
#############################################################################################################
#############################################################################################################
11/08/2017 | 16:02:24
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
11/08/2017 | 16:02:24
subprocess.call([":",">",path])
subprocess.call(["rm",path])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
11/08/2017 | 16:02:59
subprocess.call([":",">",gpg_path])"+"
"+"subprocess.call(["rm ",gpg_path])
[Errno 9] Bad file descriptor
#############################################################################################################
#############################################################################################################
12/08/2017 | 14:55:43
gears.p_test()
'module' object has no attribute 'aggressive'
#############################################################################################################
#############################################################################################################
12/08/2017 | 14:56:51
gears.p_test()
'module' object has no attribute 'aggressive'
#############################################################################################################
#############################################################################################################
12/08/2017 | 14:58:09
gears.p_test()
'module' object has no attribute 'aggressive'
#############################################################################################################
#############################################################################################################
12/08/2017 | 14:59:07
gears.p_test()
'module' object has no attribute 'aggressive'
#############################################################################################################
#############################################################################################################
12/08/2017 | 15:08:29
gears.p_test()
personality() takes exactly 8 arguments (9 given)
#############################################################################################################
#############################################################################################################
12/08/2017 | 15:11:21
gears.p_test()
personality() takes exactly 8 arguments (9 given)
#############################################################################################################
#############################################################################################################
12/08/2017 | 15:24:16
gears.p_test()
invalid literal for int() with base 10: ''
#############################################################################################################
#############################################################################################################
12/08/2017 | 18:54:51
gears.p_test()
invalid literal for int() with base 10: "2'"
#############################################################################################################
#############################################################################################################
12/08/2017 | 18:56:49
gears.p_test()
invalid literal for int() with base 10: 't'
#############################################################################################################
#############################################################################################################
12/08/2017 | 19:55:57
stalker opt == add
unsupported operand type(s) for +: 'NoneType' and 'str'
#############################################################################################################
#############################################################################################################
12/08/2017 | 19:58:43
stalker opt == add
"'bold','underline'"
#############################################################################################################
#############################################################################################################
12/08/2017 | 20:00:55
stalker opt == add
"'bold','underline'"
#############################################################################################################
#############################################################################################################
12/08/2017 | 20:03:24
stalker opt == add
unsupported operand type(s) for +: 'NoneType' and 'str'
#############################################################################################################
#############################################################################################################
12/08/2017 | 20:05:01
stalker opt == add
'bold'
#############################################################################################################
#############################################################################################################
12/08/2017 | 20:08:05
stalker opt == add
'bold'
#############################################################################################################
#############################################################################################################
12/08/2017 | 20:18:43
stalker opt == add
msg() takes exactly 4 arguments (2 given)
#############################################################################################################
#############################################################################################################
12/08/2017 | 20:19:17
stalker opt == add
msg() takes exactly 4 arguments (2 given)
#############################################################################################################
#############################################################################################################
12/08/2017 | 22:02:31
stalker opt == add
std_msg() takes exactly 4 arguments (2 given)
#############################################################################################################
#############################################################################################################
14/08/2017 | 17:09:55
stalker opt == add
std_msg() takes exactly 4 arguments (2 given)
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:48:22
subprocess.call(["w3m "+url])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:48:22
subprocess.call(["wget -qO- "+url+" | html2text"])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:48:24
gears.phone_search()
unsupported operand type(s) for +: 'NoneType' and 'str'
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:49:47
subprocess.call(["w3m "+url])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:49:47
subprocess.call(["wget -qO- "+url+" | html2text"])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:50:10
subprocess.call(["w3m "+url])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:50:10
subprocess.call(["wget -qO- "+url+" | html2text"])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:51:55
subprocess.call(["w3m "+url])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:51:55
subprocess.call(["wget -qO- "+url+" | html2text"])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:52:39
subprocess.call(["w3m "+url])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:52:40
subprocess.call(["wget -qO- "+url+" | html2text"])
[Errno 2] No such file or directory
#############################################################################################################
#############################################################################################################
16/08/2017 | 22:52:42
gears.phone_search()
global name 'gears' is not defined
#############################################################################################################